# Generated by Django 2.2 on 2020-11-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201104_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'managed': True, 'verbose_name_plural': 'profiles'},
        ),
    ]
