# Generated by Django 2.2 on 2020-11-04 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnare', '0001_initial'),
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(max_length=150)),
                ('institution', models.CharField(max_length=255, null=True)),
                ('council', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_council', to='questionnare.Council')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_country', to='questionnare.Country')),
            ],
            options={
                'verbose_name_plural': 'profiles',
                'db_table': 'profiles',
                'managed': True,
            },
        ),
    ]
