# Generated by Django 3.1.1 on 2020-09-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, null=True)),
                ('parent', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'contries',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('initial', models.CharField(max_length=25, null=True)),
                ('description', models.TextField(null=True)),
                ('logo', models.ImageField(null=True, upload_to='photos')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='questionnare.country')),
            ],
            options={
                'verbose_name_plural': 'Institutions',
                'db_table': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='questionnare.institution')),
            ],
            options={
                'verbose_name_plural': 'Respondents',
                'db_table': 'respondents',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('code', models.CharField(max_length=5)),
                ('qn_type', models.CharField(choices=[('SELECT', 'Multiple choice'), ('CHECKBOX', 'Checkbox'), ('TEXTAREA', 'Free text')], default='SELECT', max_length=50, verbose_name='Question type')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnare.category')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
            },
        ),
    ]
