# Generated by Django 3.1.1 on 2020-09-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='parent',
        ),
    ]
