# Generated by Django 3.1.1 on 2020-09-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0002_remove_country_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnare.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qn_type',
            field=models.CharField(choices=[('SELECT', 'Select One'), ('CHECKBOX', 'Select Multiple'), ('TEXTAREA', 'Free Text')], default='SELECT', max_length=50, verbose_name='Question type'),
        ),
    ]
