# Generated by Django 3.1.1 on 2020-09-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0004_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn_type',
            field=models.CharField(choices=[('SELECT', 'Select One'), ('CHECKBOX', 'Select Multiple'), ('NUMBER', 'Number'), ('TEXTAREA', 'Free Text')], default='SELECT', max_length=50, verbose_name='Question type'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnare.question')),
            ],
            options={
                'verbose_name_plural': 'Answers',
                'db_table': 'answers',
            },
        ),
    ]
