# Generated by Django 3.1.1 on 2020-09-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0007_auto_20200929_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='parent',
        ),
        migrations.AlterField(
            model_name='question',
            name='qn_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SELECT', 'Select One'), ('CHECKBOX', 'Select Multiple'), ('NUMBER', 'Number'), ('TEXTAREA', 'Free Text')], default='NONE', max_length=50, verbose_name='Question type'),
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('code', models.CharField(max_length=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='questionnare.question')),
            ],
            options={
                'verbose_name_plural': 'Sub Questions',
                'db_table': 'sub_questions',
            },
        ),
    ]
