# Generated by Django 3.1.1 on 2020-09-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0008_auto_20200929_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='qn_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SELECT', 'Select One'), ('CHECKBOX', 'Select Multiple'), ('NUMBER', 'Number'), ('TEXTAREA', 'Free Text')], default='NONE', max_length=50, verbose_name='Question type'),
        ),
    ]
