# Generated by Django 3.1.1 on 2020-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0012_auto_20200930_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subquestion',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
