# Generated by Django 3.1.1 on 2020-10-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0013_auto_20200930_0803'),
    ]

    operations = [

    ]
