# Generated by Django 3.1.1 on 2020-10-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0016_auto_20201008_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='respondent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondents', to='questionnare.respondent'),
        ),
    ]
