# Generated by Django 3.1.1 on 2020-10-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0018_auto_20201008_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnare.country'),
        ),
    ]
