# Generated by Django 3.1.1 on 2020-10-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0019_respondent_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='qn_type',
            field=models.CharField(default='None', max_length=25, null=True),
        ),
    ]
