# Generated by Django 3.1.1 on 2020-10-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0020_answer_qn_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='qn_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='sub_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnare.subquestion'),
        ),
    ]
