# Generated by Django 3.1.1 on 2020-10-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnare', '0021_auto_20201008_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnare.country'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnare.institution'),
        ),
    ]
